stages:
    - init
    - quality
    - build
    - deploy

variables:
    GIT_STRATEGY: none
    COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/cache/composer"

workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
        - if: '$CI_COMMIT_TAG || $CI_COMMIT_REF_TYPE == "tag"'
        - if: $CI_PIPELINE_SOURCE == "schedule"

cache:
    paths:
        - ~/.composer/cache
        - vendor

.job:
    image: php:8.3
    tags: [hp]
    before_script:
        - echo "Setting up environment"
        - apt-get update && apt-get install -y git unzip zip curl libicu-dev libzip-dev libxslt1-dev libjpeg-dev libpng-dev libfreetype6-dev
        - docker-php-ext-install pdo_mysql intl xsl exif gd calendar zip
        - echo "Environment setup complete"

# --- Step 1 - Init global images (download sources & composer)
sources:
    stage: init
    extends: [.job]
    script:
        - echo "Cloning repository"
        - git clone --branch "${CI_COMMIT_REF_NAME}" https://gitlab-ci-token:${CI_JOB_TOKEN}@git.quaidorsay.fr/sites_divers/Guardian.git .
        - cp DEPLOY.md app/DEPLOY.md
        - echo "Cloned repository successfully"
    artifacts:
        paths:
            - app/
        expire_in: 1h

composer:
    stage: init
    extends: [.job]
    script:
        - echo "Installing Composer"
        - mkdir -p bin
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=bin --filename=composer
        - php bin/composer --version
        - echo "Composer installed"
    artifacts:
        paths:
            - bin/composer
        expire_in: 1h

# --- Step 2: Static Analysis ---
quality:security:
    stage: quality
    extends: [.job]
    needs: [sources, composer]
    dependencies: [sources, composer]
    script:
        - cd app/
        - php ../bin/composer install --no-scripts --no-interaction
        - php ../bin/composer audit
    allow_failure: true

quality:lint:
    stage: quality
    extends: [.job]
    needs: [sources, composer]
    dependencies: [sources, composer]
    rules:
        -   if: $CI_PIPELINE_SOURCE == "merge_request_event"
            when: on_success
        -   when: never
    before_script:
        - !reference [ .job, before_script ]
        - cd app/
        - php ../bin/composer install --no-scripts --no-interaction
    script:
        - php -d memory_limit=1G bin/console cache:warmup --env=dev
        - php vendor/bin/phpstan --memory-limit=1G analyse src -c phpstan.neon
        - php vendor/bin/php-cs-fixer fix --dry-run
        - php bin/console lint:twig templates
        - php bin/console lint:yaml translations config
        - php bin/console lint:breadcrumb
        - php bin/console debug:translation --only-missing --domain=messages fr_FR


# --- Step 2: Static Tests ---
quality:tests:
    stage: quality
    extends: .job
    needs: [sources, composer]
    dependencies: [sources, composer]
    rules:
        -   if: $CI_PIPELINE_SOURCE == "merge_request_event"
            when: on_success
        -   when: never
    before_script:
        - !reference [ .job, before_script ]
        - cd app/
        - php ../bin/composer install --no-scripts --no-interaction
    services:
        - name: mariadb:10.11
          alias: database
    variables:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: 'ppe'
        MYSQL_PASSWORD: 'ppe'
        MYSQL_DATABASE: 'ppe'
        APP_ENV: 'test'
        # Database credentials
        DATABASE_HOST: database
        DATABASE_PORT: 3306
        DATABASE_NAME: ppe
        DATABASE_USER: root
        DATABASE_PASSWORD: root
        DATABASE_VERSION: 10.11.9-MariaDB
    script:
        - php bin/console doctrine:database:create --if-not-exists --no-interaction
        - php bin/console doctrine:migrations:migrate --no-interaction
        - php bin/console doctrine:fixtures:load --no-interaction --append --group=test
        - php bin/console sass:build
        - php bin/console importmap:install
        - php bin/console assets:install web
        - php bin/console asset-map:compile
        - vendor/bin/phpunit -d memory_limit=-1 --no-coverage --log-junit phpunit-report.xml --colors=never --exclude-group=separate
    artifacts:
        when: always
        reports:
            junit: app/phpunit-report.xml

# --- Step 3: Build Artifacts ---
build:
    stage: build
    extends: [ .job ]
    dependencies: [ sources, composer ]
    rules:
        -   if: '$CI_COMMIT_TAG || $CI_COMMIT_REF_TYPE == "tag"'
            when: on_success
        -   if: $CI_PIPELINE_SOURCE == "schedule"
            when: manual
        -   when: never
    script:
        # Copy files
        - mkdir -p build/app
        - cp -R app/assets build/app/assets
        - cp -R app/bin build/app/bin
        - cp -R app/config build/app/config
        - cp -R app/migrations build/app/migrations
        - cp -R app/src build/app/src
        - cp -R app/templates build/app/templates
        - cp -R app/translations build/app/translations
        - cp -R app/web build/app/web
        - cp -R app/.env build/app/.env
        - cp -R app/composer.json build/app/composer.json
        - cp -R app/composer.lock build/app/composer.lock
        - cp -R app/symfony.lock build/app/symfony.lock
        - cp -R app/importmap.php build/app/importmap.php

        # Install Composer dependencies without dev dependencies and scripts
        - cd build/app
        - php ../../bin/composer install --no-interaction --no-dev --no-progress --no-scripts
        - php ../../bin/composer dump-autoload --no-dev --classmap-authoritative

        # Build assets
        - php bin/console sass:build
        - php bin/console importmap:install
        - php bin/console assets:install web
        - php bin/console asset-map:compile

        #Back to root directory and add installation documentation
        - cd ../..
        - cp app/DEPLOY.md build/GUIDE-DE-DEPLOIEMENT.md

    artifacts:
        name: "build-${CI_COMMIT_SHORT_SHA}"
        paths:
            - build/app/*
        expire_in: 1 year


# --- Step 4: Deploy ---
.deploy:
    image: debian:latest
    stage: deploy
    dependencies: [build]
    rules:
        -   if: '$CI_COMMIT_TAG || $CI_COMMIT_REF_TYPE == "tag"'
            when: manual
        -   when: never
    before_script:
        # install pour exploiter la clé ssh
        - apt-get update -qq && apt-get install -y -qq rsync openssh-client > /dev/null 2>&1
        # Créer un fichier temporaire pour la clé SSH
        - mkdir -p ~/.ssh
        - echo "$SSH_KEY" > ~/.ssh/id_rsa
        - eval $(ssh-agent -s)
        - sed -i 's/\r//' ~/.ssh/id_rsa
        - chmod 400 ~/.ssh/id_rsa
        - ssh-add ~/.ssh/id_rsa
        - chmod 700 ~/.ssh
    script:
        - echo -e "\033[1;34m[INFO] $(date) - Deploying PPE code ...\033[0m"
        - export BUILD_DATE=$(date +"%Y%m%d%H%M%S")
        # Étape 1 : Copier les fichiers sur chaque serveur
        - |
            for HOST in $DEPLOY_HOSTS; do
                echo "==== Déploiement sur $HOST ====";
                ssh-keyscan -H $HOST >> ~/.ssh/known_hosts        
                # Synchronisation en excluant les fichiers/dossiers + Création dossier nom du tag
                export REMOTE_DIR=$(ssh $REMOTE_USER@$HOST "pwd")
                export REMOTE_USER_DIR=$(basename "$REMOTE_DIR")
                echo "Connect with $REMOTE_USER"
                echo "Create directory $REMOTE_DIR/livraison/$BUILD_DATE"
                ssh $REMOTE_USER@$HOST mkdir -p $REMOTE_DIR/livraison/$BUILD_DATE
                cp "$ENV_LOCAL_FILE" ./build/app/.env.local
            
                rsync -avq --delete ./build/app/ $REMOTE_USER@$HOST:$REMOTE_DIR/livraison/$BUILD_DATE/;

                # Remise en place des liens
                echo "Recréation des liens symboliques sur $HOST"
                ssh $REMOTE_USER@$HOST rm -rf $REMOTE_DIR/livraison/$BUILD_DATE/var/uploads
                # create shared directory
                ssh $REMOTE_USER@$HOST ln -sf /mnt/www/$REMOTE_USER_DIR/uploads $REMOTE_DIR/livraison/$BUILD_DATE/var/uploads
            done
        - |
            for HOST in $DEPLOY_HOSTS; do
                echo "==== Bascule sur $HOST ====";
                echo "Link dir $REMOTE_DIR/livraison/$BUILD_DATE to $REMOTE_DIR/site"
                ssh $REMOTE_USER@$HOST rm -f $REMOTE_DIR/site
                ssh $REMOTE_USER@$HOST ln -s $REMOTE_DIR/livraison/$BUILD_DATE $REMOTE_DIR/site
               
                # clear Opcache
                echo "command line cachetool & console"
                ssh $REMOTE_USER@$HOST "php $REMOTE_DIR/tools/cachetool.phar opcache:reset --fcgi=127.0.0.1:20024"
                ssh $REMOTE_USER@$HOST "php $REMOTE_DIR/site/bin/console doctrine:migrations:migrate --no-interaction"
                ssh $REMOTE_USER@$HOST "php $REMOTE_DIR/site/bin/console cache:clear"
                ssh $REMOTE_USER@$HOST "php $REMOTE_DIR/site/bin/console cache:pool:clear --all"
                ssh $REMOTE_USER@$HOST "php $REMOTE_DIR/site/bin/console cache:warmup"
                ssh $REMOTE_USER@$HOST "php $REMOTE_DIR/tools/cachetool.phar opcache:reset --fcgi=127.0.0.1:20024"

                 # Clean old livraison
                ssh $REMOTE_USER@$HOST bash $REMOTE_DIR/tools/clean_livraison.sh
                echo -e "\033[1;34m[INFO] Bascule sur $HOST OK !\033[0m"
            done

deploy:preprod:
    environment: preprod
    tags: [hp]
    extends: .deploy
    variables:
        REMOTE_USER: "refonte-diplo-ppe"

deploy:production:
    environment: production
    tags: [prod]
    extends: .deploy
    variables:
        REMOTE_USER: "refonte-diplo-ppe"

