providers:
    docker:
        exposedByDefault: false
    file:
        filename: /etc/traefik/dynamic_conf.yml

entryPoints:
    http:
        address: ":80"
    https:
        address: ":443"

api:
    insecure: true
