endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 400
        margin: 0
        encoding: 'UTF-8'
        error_correction_level: 'medium'
        round_block_size_mode: 'margin'
        validate_result: false
